### ISSUE TITLE
Error while deploying the app on Heroku

### ISSUE THREAD

**Issue by metao1** [transistorsoft/background-geolocation-console#48]
2018-09-13T21:55:17.000000+00:00 app[api]: Build succeeded
2018-09-13T21:55:21.053288+00:00 app[web.1]: /app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180
2018-09-13T21:55:21.053309+00:00 app[web.1]: throw new ReferenceError(messages.get("pluginUnknown", plugin, loc, i, dirname));
2018-09-13T21:55:21.053311+00:00 app[web.1]: ^
2018-09-13T21:55:21.053313+00:00 app[web.1]: 
2018-09-13T21:55:21.053316+00:00 app[web.1]: ReferenceError: Unknown plugin "react-hot-loader/babel" specified in "/app/.babelrc" at 0, attempted to resolve relative to "/app"
2018-09-13T21:55:21.053318+00:00 app[web.1]: at /app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
2018-09-13T21:55:21.053323+00:00 app[web.1]: at Function.normalisePlugins (/app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
2018-09-13T21:55:21.053320+00:00 app[web.1]: at Array.map (native)
2018-09-13T21:55:21.053324+00:00 app[web.1]: at OptionManager.mergeOptions (/app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
2018-09-13T21:55:21.053326+00:00 app[web.1]: at OptionManager.init (/app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
2018-09-13T21:55:21.053329+00:00 app[web.1]: at compile (/app/node_modules/babel-register/lib/node.js:103:45)
2018-09-13T21:55:21.053331+00:00 app[web.1]: at loader (/app/node_modules/babel-register/lib/node.js:144:14)
2018-09-13T21:55:21.053335+00:00 app[web.1]: at Module.load (module.js:494:32)
2018-09-13T21:55:21.053332+00:00 app[web.1]: at Object.require.extensions.(anonymous function) [as .js] (/app/node_modules/babel-register/lib/node.js:154:7)
2018-09-13T21:55:21.053337+00:00 app[web.1]: at tryModuleLoad (module.js:453:12)
2018-09-13T21:55:21.071440+00:00 app[web.1]: 
2018-09-13T21:55:21.086813+00:00 app[web.1]: npm ERR! Linux 4.4.0-1027-aws
2018-09-13T21:55:21.087904+00:00 app[web.1]: npm ERR! node v6.14.4
2018-09-13T21:55:21.088785+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2018-09-13T21:55:21.089505+00:00 app[web.1]: npm ERR! Exit status 1
2018-09-13T21:55:21.091266+00:00 app[web.1]: npm ERR! not with npm itself.
2018-09-13T21:55:21.087340+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2018-09-13T21:55:21.089864+00:00 app[web.1]: npm ERR!
2018-09-13T21:55:21.090208+00:00 app[web.1]: npm ERR! Failed at the background-geolocation-console@2.0.0 start script 'babel-node --presets='node6' server.js'.
2018-09-13T21:55:21.088335+00:00 app[web.1]: npm ERR! npm  v3.10.10
2018-09-13T21:55:21.090923+00:00 app[web.1]: npm ERR! If you do, this is most likely a problem with the background-geolocation-console package,
2018-09-13T21:55:21.091621+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2018-09-13T21:55:21.090574+00:00 app[web.1]: npm ERR! Make sure you have the latest version of node.js and npm installed.
2018-09-13T21:55:21.091952+00:00 app[web.1]: npm ERR!     babel-node --presets='node6' server.js
2018-09-13T21:55:21.089150+00:00 app[web.1]: npm ERR! background-geolocation-console@2.0.0 start: `babel-node --presets='node6' server.js`
2018-09-13T21:55:21.092303+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2018-09-13T21:55:21.092646+00:00 app[web.1]: npm ERR!     npm bugs background-geolocation-console
2018-09-13T21:55:21.093264+00:00 app[web.1]: npm ERR!     npm owner ls background-geolocation-console
2018-09-13T21:55:21.100700+00:00 app[web.1]: 
2018-09-13T21:55:21.092933+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2018-09-13T21:55:21.093601+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2018-09-13T21:55:21.101080+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2018-09-13T21:55:21.101359+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2018-09-13T21:55:21.178952+00:00 heroku[web.1]: State changed from starting to crashed
2018-09-13T21:55:21.180768+00:00 heroku[web.1]: State changed from crashed to starting
2018-09-13T21:55:21.165913+00:00 heroku[web.1]: Process exited with status 1
2018-09-13T21:55:26.866324+00:00 heroku[web.1]: Starting process with command `npm start`
2018-09-13T21:55:30.737785+00:00 app[web.1]: 
2018-09-13T21:55:30.737804+00:00 app[web.1]: > babel-node --presets='node6' server.js
2018-09-13T21:55:30.737806+00:00 app[web.1]: 
2018-09-13T21:55:30.737802+00:00 app[web.1]: > background-geolocation-console@2.0.0 start /app
2018-09-13T21:55:32.991705+00:00 app[web.1]: /app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180
2018-09-13T21:55:32.991724+00:00 app[web.1]: throw new ReferenceError(messages.get("pluginUnknown", plugin, loc, i, dirname));
2018-09-13T21:55:32.991726+00:00 app[web.1]: ^
2018-09-13T21:55:32.991728+00:00 app[web.1]

**Comment by kiddkevin00** [comment]
Do you create 2 environment variables (either in the heroku dashboard, or by executing heroku config:set <VARIABLE_NAME>=<VARIABLE_VALUE>)?
- NPM_CONFIG_PRODUCTION = false : It will tell heroku to install devDependencies (and not only dependencies), required to build browserify's bundle.min.js file

I just deploy on Heroku successfully with that variable set.
