### ISSUE TITLE
Unknown plugin "react-hot-loader/babel"

### ISSUE THREAD

**Issue by marking11** [transistorsoft/background-geolocation-console#60]
Hello,
I tried to run the server but i have this error: Unknown plugin "react-hot-loader/babel"

ReferenceError: Unknown plugin "react-hot-loader/babel" specified in "/Users/mac/Desktop/serverside/.babelrc" at 0, attempted to resolve relative to "/Users/mac/Desktop/serverside"
    at /Users/mac/Desktop/serverside/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/mac/Desktop/serverside/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/mac/Desktop/serverside/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/mac/Desktop/serverside/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/Users/mac/Desktop/serverside/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/mac/Desktop/serverside/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/mac/Desktop/serverside/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! background-geolocation-console@2.0.0 server: `babel-node --presets='node6' server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the background-geolocation-console@2.0.0 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac/.npm/_logs/2019-05-14T14_37_43_629Z-debug.log

**Comment by christocracy** [comment]
And you followed the [Setup Instructions](https://github.com/transistorsoft/background-geolocation-console#install)?

**Comment by marking11** [comment]
It works now thanks
