### ISSUE TITLE
Couldn't find preset "'node6'" relative to directory "C:\\xxx\\xxx\\xxx\\background-geolocation-console"

### ISSUE THREAD

**Issue by sfdfklskldf** [transistorsoft/background-geolocation-console#63]
Environment:

- Windows 10 64 Bit
- node -v : v10.16.0
- npm -v : 6.9.0
- cordova -v : 9.0.0 (cordova-lib@9.0.1)
- using git bash 

Steps to reproduce:

1.  git clone https://github.com/transistorsoft/background-geolocation-console.git
2.  cd background-geolocation-console
3. npm install
```
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
npm WARN deprecated postcss-cssnext@2.11.0: 'postcss-cssnext' has been deprecated in favor of 'postcss-preset-env'. Read more at https://moox.io/blog/deprecating-cssnext/
npm WARN deprecated @babel/polyfill@7.4.4: 🚨 As of Babel 7.4.0, this
npm WARN deprecated package has been deprecated in favor of directly
npm WARN deprecated including core-js/stable (to polyfill ECMAScript
npm WARN deprecated features) and regenerator-runtime/runtime
npm WARN deprecated (needed to use transpiled generator functions):
npm WARN deprecated
npm WARN deprecated   > import "core-js/stable";
npm WARN deprecated   > import "regenerator-runtime/runtime";
npm WARN deprecated point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.

> sqlite3@4.0.9 install C:\xxx\xxx\xxx\background-geolocation-console\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
[sqlite3] Success: "C:\xxx\xxx\xxx\background-geolocation-console\node_modules\sqlite3\lib\binding\node-v64-win32-x64\node_sqlite3.node" is installed via remote

> core-js@2.6.9 postinstall C:\xxx\xxx\xxx\background-geolocation-console\node_modules\core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN The package postcss-cssnext is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1520 packages from 974 contributors and audited 14798 packages in 37.297s
found 10 vulnerabilities (1 low, 4 moderate, 5 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```
4. npm run server
$ npm run server
```

> background-geolocation-console@2.0.0 server C:\xxx\xxx\xxx\background-geolocation-console
> babel-node --presets='node6' server.js

C:\xxx\xxx\xxx\background-geolocation-console\node_modules\babel-core\lib\transformation\file\options\option-manager.js:328
        throw e;
        ^

Error: Couldn't find preset "'node6'" relative to directory "C:\\xxx\\xxx\\xxx\\background-geolocation-console"
    at C:\xxx\xxx\xxx\background-geolocation-console\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (C:\xxx\xxx\xxx\background-geolocation-console\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (C:\xxx\xxx\xxx\background-geolocation-console\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (C:\xxx\xxx\xxx\background-geolocation-console\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (C:\xxx\xxx\xxx\background-geolocation-console\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at compile (C:\xxx\xxx\xxx\background-geolocation-console\node_modules\babel-register\lib\node.js:103:45)
    at loader (C:\xxx\xxx\xxx\background-geolocation-console\node_modules\babel-register\lib\node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (C:\xxx\xxx\xxx\background-geolocation-console\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! background-geolocation-console@2.0.0 server: `babel-node --presets='node6' server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the background-geolocation-console@2.0.0 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2019-07-31T08_03_20_781Z-debug.log

```

Potentially this is a duplicate of https://github.com/transistorsoft/background-geolocation-console/issues/37 

Is there any suggested solution to fix it? Could this solution be added to the documentation of the readme page?

**Comment by sahyun1** [comment]
I have the same issue

**Comment by Sigura** [comment]
we do not use `babel-node` anymore.
